const cityLinks = {
    Bengaluru:{
            SearchResult:["PG in Bangalore",
                "PG in Bellandur",
                "PG for boys in Bangalore",
                "PG for boys in Bellandur",
                "PG for girls in Bangalore",
                "PG for girls in Bellandur",
                "Unisex PG in Bangalore",
                "Unisex PG in Bellandur",
                "Room for rent in Bangalore",
                "Room for rent in Bellandur",
                "Room for rent for boys in Bangalore",
                "Room for rent for boys in Bellandur",
                "Room for rent for girls in Bangalore",
                "Room for rent for girls in Bellandur",
                "1 RK on rent in Bangalore",
                "1 RK on rent in Bellandur",
                "1 RK on rent for boys in Bangalore",
                "1 RK on rent for boys in Bellandur",
                "1 RK on rent for girls in Bangalore",
                "1 RK on rent for girls in Bellandur",
                "1 BHK House for rent in Bangalore",
                "1 BHK House for rent in Bellandur",
                "2 BHK House for rent in Bangalore",
                "2 BHK House for rent in Bellandur",
                "3 BHK House for rent in Bangalore",
                "3 BHK House for rent in Bellandur",
                "4 BHK House for rent in Bangalore",
                "4 BHK House for rent in Bellandur"],

            CommonRoom:["PG in HSR Layout",
                "PG in Marathahalli",
                "PG for boys in HSR Layout",
                "PG for boys in Marathahalli",
                "PG for girls in HSR Layout",
                "PG for girls in Marathahalli",
                "Unisex PG in HSR Layout",
                "Unisex PG in Marathahalli",
                "Room for rent in Hsr Layout",
                "Room for rent in Marathahalli",
                "Room for rent for boys in Hsr Layout",
                "Room for rent for boys in Marathahalli",
                "Room for rent for girls in Hsr Layout",
                "Room for rent for girls in Marathahalli",
                "1 RK on rent in Hsr Layout",
                "1 RK on rent in Marathahalli",
                "1 RK on rent for boys in Hsr Layout",
                "1 RK on rent for boys in Marathahalli",
                "1 RK on rent for girls in Hsr Layout",
                "1 RK on rent for girls in Marathahalli",
                "1 BHK House for rent in Hsr Layout",
                "1 BHK House for rent in Marathahalli",
                "2 BHK House for rent in Hsr Layout",
                "2 BHK House for rent in Marathahalli",
                "3 BHK House for rent in Hsr Layout",
                "3 BHK House for rent in Marathahalli",
                "4 BHK House for rent in Hsr Layout",
                "4 BHK House for rent in Marathahalli"],

            CommonPG:["PG in Mahadevapura",
                "PG in Whitefield",
                "PG for boys in Mahadevapura",
                "PG for boys in Whitefield",
                "PG for girls in Mahadevapura",
                "PG for girls in Whitefield",
                "Unisex PG in Mahadevapura",
                "Unisex PG in Whitefield",
                "Room for rent in Mahadevapura",
                "Room for rent in Whitefield",
                "Room for rent for boys in Mahadevapura",
                "Room for rent for boys in Whitefield",
                "Room for rent for girls in Mahadevapura",
                "Room for rent for girls in Whitefield",
                "1 RK on rent in Mahadevapura",
                "1 RK on rent in Whitefield",
                "1 RK on rent for boys in Mahadevapura",
                "1 RK on rent for boys in Whitefield",
                "1 RK on rent for girls in Mahadevapura",
                "1 RK on rent for girls in Whitefield",
                "1 BHK House for rent in Mahadevapura",
                "1 BHK House for rent in Whitefield",
                "2 BHK House for rent in Mahadevapura",
                "2 BHK House for rent in Whitefield",
                "3 BHK House for rent in Mahadevapura",
                "3 BHK House for rent in Whitefield",
                "4 BHK House for rent in Mahadevapura",
                "4 BHK House for rent in Whitefield"]
    },

    Chennai:{
        SearchResult:["PG in Chennai",
            "PG in Pallikaranai",
            "PG for boys in Chennai",
            "PG for boys in Pallikaranai",
            "PG for girls in Chennai",
            "PG for girls in Pallikaranai",
            "Unisex PG in Chennai",
            "Unisex PG in Pallikaranai",
            "Room for rent in Chennai",
            "Room for rent in Pallikaranai",
            "Room for rent for boys in Chennai",
            "Room for rent for boys in Pallikaranai",
            "Room for rent for girls in Chennai",
            "Room for rent for girls in Pallikaranai",
            "1 RK on rent in Chennai",
            "1 RK on rent in Pallikaranai",
            "1 RK on rent for boys in Chennai",
            "1 RK on rent for boys in Pallikaranai",
            "1 RK on rent for girls in Chennai",
            "1 RK on rent for girls in Pallikaranai",
            "1 BHK House for rent in Chennai",
            "1 BHK House for rent in Pallikaranai",
            "2 BHK House for rent in Chennai",
            "2 BHK House for rent in Pallikaranai",
            "3 BHK House for rent in Chennai",
            "3 BHK House for rent in Pallikaranai",
            "4 BHK House for rent in Chennai",
            "4 BHK House for rent in Pallikaranai"],
        CommonRoom:["PG in Sholinganallur",
            "PG in Siruseri",
            "PG for boys in Sholinganallur",
            "PG for boys in Siruseri",
            "PG for girls in Sholinganallur",
            "PG for girls in Siruseri",
            "Unisex PG in Sholinganallur",
            "Unisex PG in Siruseri",
            "Room for rent in Sholinganallur",
            "Room for rent in Siruseri",
            "Room for rent for boys in Sholinganallur",
            "Room for rent for boys in Siruseri",
            "Room for rent for girls in Sholinganallur",
            "Room for rent for girls in Siruseri",
            "1 RK on rent in Sholinganallur",
            "1 RK on rent in Siruseri",
            "1 RK on rent for girls in Sholinganallur",
            "1 RK on rent for girls in Siruseri",
            "1 RK on rent for boys in Sholinganallur",
            "1 RK on rent for boys in Siruseri",
            "1 BHK House for rent in Sholinganallur",
            "1 BHK House for rent in Siruseri",
            "2 BHK House for rent in Sholinganallur",
            "2 BHK House for rent in Siruseri",
            "3 BHK House for rent in Sholinganallur",
            "3 BHK House for rent in Siruseri",
            "4 BHK House for rent in Sholinganallur",
            "4 BHK House for rent in Siruseri"],
        CommonPG:["PG in Thuraipakkam",
            "PG in Velachery",
            "PG for boys in Thuraipakkam",
            "PG for boys in Velachery",
            "PG for girls in Thuraipakkam",
            "PG for girls in Velachery",
            "Unisex PG in Thuraipakkam",
            "Unisex PG in Velachery",
            "Room for rent in Thuraipakkam",
            "Room for rent in Velachery",
            "Room for rent for boys in Thuraipakkam",
            "Room for rent for boys in Velachery",
            "Room for rent for girls in Thuraipakkam",
            "Room for rent for girls in Velachery",
            "1 RK on rent in Thuraipakkam",
            "1 RK on rent in Velachery",
            "1 RK on rent for boys in Thuraipakkam",
            "1 RK on rent for boys in Velachery",
            "1 RK on rent for girls in Thuraipakkam",
            "1 RK on rent for girls in Velachery",
            "1 BHK House for rent in Thuraipakkam",
            "1 BHK House for rent in Velachery",
            "2 BHK House for rent in Thuraipakkam",
            "2 BHK House for rent in Velachery",
            "3 BHK House for rent in Thuraipakkam",
            "3 BHK House for rent in Velachery",
            "4 BHK House for rent in Thuraipakkam",
            "4 BHK House for rent in Velachery"]
    },

    Delhi:{
        SearchResult:["PG in Delhi",
            "PG in Greater Kailash 1",
            "PG for boys in Delhi",
            "PG for boys in Greater Kailash 1",
            "PG for girls in Delhi",
            "PG for girls in Greater Kailash 1",
            "Unisex PG in Delhi",
            "Unisex PG in Greater Kailash 1",
            "Room for rent in Delhi",
            "Room for rent in Greater Kailash 1",
            "Room for rent for boys in Delhi",
            "Room for rent for boys in Greater Kailash 1",
            "Room for rent for girls in Delhi",
            "Room for rent for girls in Greater Kailash 1",
            "1 RK on rent in Delhi",
            "1 RK on rent in Greater Kailash 1",
            "1 RK on rent for boys in Delhi",
            "1 RK on rent for boys in Greater Kailash 1",
            "1 RK on rent for girls in Delhi",
            "1 RK on rent for girls in Greater Kailash 1",
            "1 BHK House for rent in Delhi",
            "1 BHK House for rent in Greater Kailash 1",
            "2 BHK House for rent in Delhi",
            "2 BHK House for rent in Greater Kailash 1",
            "3 BHK House for rent in Delhi",
            "3 BHK House for rent in Greater Kailash 1",
            "4 BHK House for rent in Delhi",
            "4 BHK House for rent in Greater Kailash 1"],
        CommonRoom:["PG in Kalkaji",
            "PG in Mayur Vihar Phase 1",
            "PG for boys in Kalkaji",
            "PG for boys in Mayur Vihar Phase 1",
            "PG for girls in Kalkaji",
            "PG for girls in Mayur Vihar Phase 1",
            "Unisex PG in Kalkaji",
            "Unisex PG in Mayur Vihar Phase 1",
            "Room for rent in Kalkaji",
            "Room for rent in Mayur Vihar Phase 1",
            "Room for rent for boys in Kalkaji",
            "Room for rent for boys in Mayur Vihar Phase 1",
            "Room for rent for girls in Kalkaji",
            "Room for rent for girls in Mayur Vihar Phase 1",
            "1 RK on rent in Kalkaji",
            "1 RK on rent in Mayur Vihar Phase 1",
            "1 RK on rent for boys in Kalkaji",
            "1 RK on rent for boys in Mayur Vihar Phase 1",
            "1 RK on rent for girls in Kalkaji",
            "1 RK on rent for girls in Mayur Vihar Phase 1",
            "1 BHK House for rent in Kalkaji",
            "1 BHK House for rent in Mayur Vihar Phase 1",
            "2 BHK House for rent in Kalkaji",
            "2 BHK House for rent in Mayur Vihar Phase 1",
            "3 BHK House for rent in Kalkaji",
            "3 BHK House for rent in Mayur Vihar Phase 1",
            "3 BHK House for rent in Kalkaji",
            "3 BHK House for rent in Mayur Vihar Phase 1"],
        CommonPG:["PG in Sarita Vihar",
            "PG in Sector 10 Dwarka",
            "PG for boys in Sarita Vihar",
            "PG for boys in Sector 10 Dwarka",
            "PG for girls in Sarita Vihar",
            "PG for girls in Sector 10 Dwarka",
            "Unisex PG in Sarita Vihar",
            "Unisex PG in Sector 10 Dwarka",
            "Room for rent in Sarita Vihar",
            "Room for rent in Sector 10 Dwarka",
            "Room for rent for boys in Sarita Vihar",
            "Room for rent for boys in Sector 10 Dwarka",
            "Room for rent for girls in Sarita Vihar",
            "Room for rent for girls in Sector 10 Dwarka",
            "1 RK on rent in Sarita Vihar",
            "1 RK on rent in Sector 10 Dwarka",
            "1 RK on rent for boys in Sarita Vihar",
            "1 RK on rent for boys in Sector 10 Dwarka",
            "1 RK on rent for girls in Sarita Vidar",
            "1 RK on rent for girls in Sector 10 Dwarka",
            "1 BHK House for rent in Sarita Vihar",
            "1 BHK House for rent in Sector 10 Dwarka",
            "2 BHK House for rent in Sarita Vihar",
            "2 BHK House for rent in Sector 10 Dwarka",
            "3 BHK House for rent in Sarita Vihar",
            "3 BHK House for rent in Sector 10 Dwarka",
            "4 BHK House for rent in Sarita Vihar",
            "4 BHK House for rent in Sector 10 Dwarka"]
    },

    Gurgaon:{
        SearchResult:["PG in Gurgaon",
            "PG in Dlf City Phase 3",
            "PG for boys in Gurgaon",
            "PG for boys in Dlf City Phase 3",
            "PG for girls in Gurgaon",
            "PG for girls in Dlf City Phase 3",
            "Unisex PG in Gurgaon",
            "Unisex PG in Dlf City Phase 3",
            "Room for rent in Gurgaon",
            "Room for rent in Dlf City Phase 3",
            "Room for rent for boys in Gurgaon",
            "Room for rent for boys in Dlf City Phase 3",
            "Room for rent for girls in Gurgaon",
            "Room for rent for girls in Dlf City Phase 3",
            "1 RK on rent in Gurgaon",
            "1 RK on rent in Dlf City Phase 3",
            "1 RK on rent for boys in Gurgaon",
            "1 RK on rent for boys in Dlf City Phase 3",
            "1 RK on rent for girls in Gurgaon",
            "1 RK on rent for girls in Dlf City Phase 3",
            "1 BHK House for rent in Gurgaon",
            "1 BHK House for rent in Dlf City Phase 3",
            "2 BHK House for rent in Gurgaon",
            "2 BHK House for rent in Dlf City Phase 3",
            "3 BHK House for rent in Gurgaon",
            "3 BHK House for rent in Dlf City Phase 3",
            "4 BHK House for rent in Gurgaon",
            "4 BHK House for rent in Dlf City Phase 3"],
        CommonRoom:["PG in Sector 39",
            "PG in Sector 43",
            "PG for boys in Sector 39",
            "PG for boys in Sector 43",
            "PG for girls in Sector 39",
            "PG for girls in Sector 43",
            "Unisex PG in Sector 39",
            "Unisex PG in Sector 43",
            "Room for rent in Sector 39",
            "Room for rent in Sector 43",
            "Room for rent for boys in Sector 39",
            "Room for rent for boys in Sector 43",
            "Room for rent for girls in Sector 39",
            "Room for rent for girls in Sector 43",
            "1 RK on rent in Sector 39",
            "1 RK on rent in Sector 43",
            "1 RK on rent for boys in Sector 39",
            "1 RK on rent for boys in Sector 43",
            "1 RK on rent for girls in Sector 39",
            "1 RK on rent for girls in Sector 43",
            "1 BHK House for rent in Sector 39",
            "1 BHK House for rent in Sector 43",
            "2 BHK House for rent in Sector 39",
            "2 BHK House for rent in Sector 43",
            "3 BHK House for rent in Sector 39",
            "3 BHK House for rent in Sector 43",
            "4 BHK House for rent in Sector 39",
            "4 BHK House for rent in Sector 43"],
        CommonPG:["PG in Sector 52",
            "PG in Sector 57",
            "PG for boys in Sector 52",
            "PG for boys in Sector 57",
            "PG for girls in Sector 52",
            "PG for girls in Sector 57",
            "Unisex PG in Sector 52",
            "Unisex PG in Sector 57",
            "Room for rent in Sector 52",
            "Room for rent in Sector 57",
            "Room for rent for boys in Sector 52",
            "Room for rent for boys in Sector 57",
            "Room for rent for girls in Sector 52",
            "Room for rent for girls in Sector 57",
            "1 RK on rent in Sector 52",
            "1 RK on rent in Sector 57",
            "1 RK on rent for boys in Sector 52",
            "1 RK on rent for boys in Sector 57",
            "1 RK on rent for girls in Sector 52",
            "1 RK on rent for girls in Sector 57",
            "1 BHK House for rent in Sector 52",
            "1 BHK House for rent in Sector 57",
            "2 BHK House for rent in Sector 52",
            "2 BHK House for rent in Sector 57",
            "3 BHK House for rent in Sector 52",
            "3 BHK House for rent in Sector 57",
            "4 BHK House for rent in Sector 52",
            "4 BHK House for rent in Sector 57"]
    },

    Hyderabad:{
        SearchResult:["PG in Hyderabad",
            "PG in Gachibowli",
            "PG for boys in Hyderabad",
            "PG for boys in Gachibowli",
            "PG for girls in Hyderabad",
            "PG for girls in Gachibowli",
            "Unisex PG in Hyderabad",
            "Unisex PG in Gachibowli",
            "Room for rent in Hyderabad",
            "Room for rent in Gachibowli",
            "Room for rent for boys in Hyderabad",
            "Room for rent for boys in Gachibowli",
            "Room for rent for girls in Hyderabad",
            "Room for rent for girls in Gachibowli",
            "1 RK on rent in Hyderabad",
            "1 RK on rent in Gachibowli",
            "1 RK on rent for boys in Hyderabad",
            "1 RK on rent for boys in Gachibowli",
            "1 RK on rent for girls in Hyderabad",
            "1 RK on rent for girls in Gachibowli",
            "1 BHK House for rent in Hyderabad",
            "1 BHK House for rent in Gachibowli",
            "2 BHK House for rent in Hyderabad",
            "2 BHK House for rent in Gachibowli",
            "3 BHK House for rent in Hyderabad",
            "3 BHK House for rent in Gachibowli",
            "4 BHK House for rent in Hyderabad",
            "4 BHK House for rent in Gachibowli"],
        CommonRoom:["PG in Kondapur",
            "PG in Kukatpally",
            "PG for boys in Kondapur",
            "PG for boys in Kukatpally",
            "PG for girls in Kondapur",
            "PG for girls in Kukatpally",
            "Unisex PG in Kondapur",
            "Unisex PG in Kukatpally",
            "Room for rent in Kondapur",
            "Room for rent in Kukatpally",
            "Room for rent for boys in Kondapur",
            "Room for rent for boys in Kukatpally",
            "Room for rent for girls in Kondapur",
            "Room for rent for girls in Kukatpally",
            "1 RK on rent in Kondapur",
            "1 RK on rent in Kukatpally",
            "1 RK on rent for boys in Kondapur",
            "1 RK on rent for boys in Kukatpally",
            "1 RK on rent for girls in Kondapur",
            "1 RK on rent for girls in Kukatpally",
            "1 BHK House for rent in Kondapur",
            "1 BHK House for rent in Kukatpally",
            "2 BHK House for rent in Kondapur",
            "2 BHK House for rent in Kukatpally",
            "3 BHK House for rent in Kondapur",
            "3 BHK House for rent in Kukatpally",
            "4 BHK House for rent in Kondapur",
            "4 BHK House for rent in Kukatpally"],
        CommonPG:["PG in Madhapur",
            "PG in Manikonda",
            "PG for boys in Madhapur",
            "PG for boys in Manikonda",
            "PG for girls in Madhapur",
            "PG for girls in Manikonda",
            "Unisex PG in Madhapur",
            "Unisex PG in Manikonda",
            "Room for rent in Madhapur",
            "Room for rent in Manikonda",
            "Room for rent for boys in Madhapur",
            "Room for rent for boys in Manikonda",
            "Room for rent for girls in Madhapur",
            "Room for rent for girls in Manikonda",
            "1 RK on rent in Madhapur",
            "1 RK on rent in Manikonda",
            "1 RK on rent for boys in Madhapur",
            "1 RK on rent for boys in Manikonda",
            "1 RK on rent for girls in Madhapur",
            "1 RK on rent for girls in Manikonda",
            "1 BHK House for rent in Madhapur",
            "1 BHK House for rent in Manikonda",
            "2 BHK House for rent in Madhapur",
            "2 BHK House for rent in Manikonda",
            "3 BHK House for rent in Madhapur",
            "3 BHK House for rent in Manikonda",
            "4 BHK House for rent in Madhapur",
            "4 BHK House for rent in Manikonda"]
    },

    Jaipur:{
        SearchResult:[],
        CommonRoom:[],
        CommonPG:[]
    },

    Kolkata:{
        SearchResult:[],
        CommonRoom:[],
        CommonPG:[]
    },

    Mumbai:{
        SearchResult:["PG in Mumbai",
            "PG in Andheri East",
            "PG in Santacruz East",
            "PG for boys in Malad West",
            "PG for boys in Powai",
            "PG for girls in Andheri West",
            "PG for girls in Kurla West",
            "Unisex PG in Mumbai",
            "Unisex PG in Andheri East",
            "Unisex PG in Santacruz East",
            "Room for rent in Mumbai",
            "Room for rent in Andheri East",
            "Room for rent in Santacruz East",
            "Room for rent for boys in Andheri West",
            "Room for rent for boys in Kurla West",
            "Room for rent for girls in Andheri East",
            "Room for rent for girls in Andheri West",
            "1 RK on rent in Andheri West",
            "1 RK on rent in Kurla West",
            "1 RK on rent for boys in Andheri East",
            "1 RK on rent for boys in Andheri West",
            "1 RK on rent for girls in Mumbai",
            "1 RK on rent for girls in Andheri East",
            "1 RK on rent for girls in Santacruz East",
            "1 BHK House for rent in Andheri West",
            "1 BHK House for rent in Kurla West",
            "2 BHK House for rent in Andheri East",
            "2 BHK House for rent in Andheri West",
            "3 BHK House for rent in Mumbai",
            "3 BHK House for rent in Andheri East",
            "3 BHK House for rent in Santacruz East",
            "4 BHK House for rent in Mumbai",
            "4 BHK House for rent in Santacruz East"],
        CommonRoom:["PG in Andheri West",
            "PG in Kurla West",
            "PG for boys in Mumbai",
            "PG for boys in Andheri East",
            "PG for boys in Santacruz East",
            "PG for girls in Malad West",
            "PG for girls in Powai",
            "Unisex PG in Andheri West",
            "Unisex PG in Kurla West",
            "Room for rent in Andheri West",
            "Room for rent in Kurla West",
            "Room for rent for boys in Mumbai",
            "Room for rent for boys in Malad West",
            "Room for rent for boys in Powai",
            "Room for rent for girls in Kurla West",
            "Room for rent for girls in Malad West",
            "1 RK on rent in Mumbai",
            "1 RK on rent in Malad West",
            "1 RK on rent in Powai",
            "1 RK on rent for boys in Kurla West",
            "1 RK on rent for boys in Malad West",
            "1 RK on rent for girls in Andheri West",
            "1 RK on rent for girls in Kurla West",
            "1 BHK House for rent in Mumbai",
            "1 BHK House for rent in Malad West",
            "1 BHK House for rent in Powai",
            "2 BHK House for rent in Kurla West",
            "2 BHK House for rent in Malad West",
            "3 BHK House for rent in Andheri West",
            "3 BHK House for rent in Kurla West",
            "4 BHK House for rent in Andheri East",
            "4 BHK House for rent in Andheri West",
            "4 BHK House for rent in Powai"],
        CommonPG:["PG in Malad West",
            "PG in Powai",
            "PG for boys in Andheri West",
            "PG for boys in Kurla West",
            "PG for girls in Mumbai",
            "PG for girls in Andheri East",
            "PG for girls in Santacruz East",
            "Unisex PG in Malad West",
            "Unisex PG in Powai",
            "Room for rent in Malad West",
            "Room for rent in Powai",
            "Room for rent for boys in Andheri East",
            "Room for rent for boys in Santacruz East",
            "Room for rent for girls in Mumbai",
            "Room for rent for girls in Powai",
            "Room for rent for girls in Santacruz East",
            "1 RK on rent in Andheri East",
            "1 RK on rent in Santacruz East",
            "1 RK on rent for boys in Mumbai",
            "1 RK on rent for boys in Powai",
            "1 RK on rent for boys in Santacruz East",
            "1 RK on rent for girls in Malad West",
            "1 RK on rent for girls in Powai",
            "1 BHK House for rent in Andheri East",
            "1 BHK House for rent in Santacruz East",
            "2 BHK House for rent in Mumbai",
            "2 BHK House for rent in Powai",
            "2 BHK House for rent in Santacruz East",
            "3 BHK House for rent in Malad West",
            "3 BHK House for rent in Powai",
            "4 BHK House for rent in Kurla West",
            "4 BHK House for rent in Malad West"]
    },

    Patna:{
        SearchResult:[],
        CommonRoom:[],
        CommonPG:[]
    },

    Pune:{
        SearchResult:["PG in Pune",
            "PG in Hinjewadi",
            "PG for boys in Pune",
            "PG for boys in Hinjewadi",
            "PG for girls in Pune",
            "PG for girls in Hinjewadi",
            "Unisex PG in Pune",
            "Unisex PG in Hinjewadi",
            "Room for rent in Pune",
            "Room for rent in Hinjewadi",
            "Room for rent for boys in Pune",
            "Room for rent for boys in Hinjewadi",
            "Room for rent for girls in Pune",
            "Room for rent for girls in Hinjewadi",
            "1 RK on rent in Pune",
            "1 RK on rent in Hinjewadi",
            "1 RK on rent for boys in Pune",
            "1 RK on rent for boys in Hinjewadi",
            "1 RK on rent for girls in Pune",
            "1 RK on rent for girls in Hinjewadi",
            "1 BHK House for rent in Pune",
            "1 BHK House for rent in Hinjewadi",
            "2 BHK House for rent in Pune",
            "2 BHK House for rent in Hinjewadi",
            "3 BHK House for rent in Pune",
            "3 BHK House for rent in Hinjewadi",
            "4 BHK House for rent in Pune",
            "4 BHK House for rent in Hinjewadi"],
        CommonRoom:["PG in Viman Nagar",
            "PG in Aundh",
            "PG for boys in Viman Nagar",
            "PG for boys in Aundh",
            "PG for girls in Viman Nagar",
            "PG for girls in Aundh",
            "Unisex PG in Viman Nagar",
            "Unisex PG in Aundh",
            "Room for rent in Viman Nagar",
            "Room for rent in Aundh",
            "Room for rent for boys in Viman Nagar",
            "Room for rent for boys in Aundh",
            "Room for rent for girls in Viman Nagar",
            "Room for rent for girls in Aundh",
            "1 RK on rent in Viman Nagar",
            "1 RK on rent in Aundh",
            "1 RK on rent for boys in Viman Nagar",
            "1 RK on rent for boys in Aundh",
            "1 RK on rent for girls in Viman Nagar",
            "1 RK on rent for girls in Aundh",
            "1 BHK House for rent in Viman Nagar",
            "1 BHK House for rent in Aundh",
            "2 BHK House for rent in Viman Nagar",
            "2 BHK House for rent in Aundh",
            "3 BHK House for rent in Viman Nagar",
            "3 BHK House for rent in Aundh",
            "4 BHK House for rent in Viman Nagar",
            "4 BHK House for rent in Aundh"],
        CommonPG:["PG in Kharadi",
            "PG in Wakad",
            "PG for boys in Kharadi",
            "PG for boys in Wakad",
            "PG for girls in Kharadi",
            "PG for girls in Wakad",
            "Unisex PG in Kharadi",
            "Unisex PG in Wakad",
            "Room for rent in Kharadi",
            "Room for rent in Wakad",
            "Room for rent for boys in Kharadi",
            "Room for rent for boys in Wakad",
            "Room for rent for girls in Kharadi",
            "Room for rent for girls in Wakad",
            "1 RK on rent in Kharadi",
            "1 RK on rent in Wakad",
            "1 RK on rent for boys in Kharadi",
            "1 RK on rent for boys in Wakad",
            "1 RK on rent for girls in Kharadi",
            "1 RK on rent for girls in Wakad",
            "1 BHK House for rent in Kharadi",
            "1 BHK House for rent in Wakad",
            "2 BHK House for rent in Kharadi",
            "2 BHK House for rent in Wakad",
            "3 BHK House for rent in Kharadi",
            "3 BHK House for rent in Wakad",
            "4 BHK House for rent in Kharadi",
            "4 BHK House for rent in Wakad"]
    },
} 
export default cityLinks;