const cityLinks = {
    Bengaluru:{
            SearchResult:["Room for rent in Bangalore",
                "Room for rent in Bellandur",
                "Room for rent for boys in Bangalore",
                "Room for rent for boys in Bellandur",
                "Room for rent for girls in Bangalore",
                "Room for rent for girls in Bellandur",
                "House for rent in Bangalore",
                "House for rent in Bellandur",
                "1RK on rent in Bangalore",
                "1RK on rent in Bellandur",
                "1RK on rent for boys in Bangalore",
                "1RK on rent for boys in Bellandur",
                "1RK on rent for girls in Bangalore",
                "1RK on rent for girls in Bellandur",
                "1 BHK House for rent in Bangalore",
                "1 BHK House for rent in Bellandur",
                "2 BHK House for rent in Bangalore",
                "2 BHK House for rent in Bellandur",
                "3 BHK House for rent in Bangalore",
                "3 BHK House for rent in Bellandur",
                "4 BHK House for rent in Bangalore",
                "4 BHK House for rent in Bellandur"],

            CommonRoom:["Room for rent in Hsr Layout",
                "Room for rent in Marathahalli",
                "Room for rent for boys in Hsr Layout",
                "Room for rent for boys in Marathahalli",
                "Room for rent for girls in Hsr Layout",
                "Room for rent for girls in Marathahalli",
                "House for rent in Hsr Layout",
                "House for rent in Marathahalli",
                "1RK on rent in Hsr Layout",
                "1RK on rent in Marathahalli",
                "1RK on rent for boys in Hsr Layout",
                "1RK on rent for boys in Marathahalli",
                "1RK on rent for girls in Hsr Layout",
                "1RK on rent for girls in Marathahalli",
                "1 BHK House for rent in Hsr Layout",
                "1 BHK House for rent in Marathahalli",
                "2 BHK House for rent in Hsr Layout",
                "2 BHK House for rent in Marathahalli",
                "3 BHK House for rent in Hsr Layout",
                "3 BHK House for rent in Marathahalli",
                "4 BHK House for rent in Hsr Layout",
                "4 BHK House for rent in Marathahalli"],

            CommonPG:["Room for rent in Mahadevapura",
                "Room for rent in White eld",
                "Room for rent for boys in Mahadevapura",
                "Room for rent for boys in White eld",
                "Room for rent for girls in Mahadevapura",
                "Room for rent for girls in White eld",
                "House for rent in Mahadevapura",
                "House for rent in White eld",
                "1RK on rent in Mahadevapura",
                "1RK on rent in White eld",
                "1RK on rent for boys in Mahadevapura",
                "1RK on rent for boys in White eld",
                "1RK on rent for girls in Mahadevapura",
                "1RK on rent for girls in White eld",
                "1 BHK House for rent in Mahadevapura",
                "1 BHK House for rent in White eld",
                "2 BHK House for rent in Mahadevapura",
                "2 BHK House for rent in White eld",
                "3 BHK House for rent in Mahadevapura",
                "3 BHK House for rent in White eld",
                "4 BHK House for rent in Mahadevapura",
                "4 BHK House for rent in White eld"]
    },

    Chennai:{
        SearchResult:["Room for rent in Chennai",
            "Room for rent in Pallikaranai",
            "Room for rent for boys in Chennai",
            "Room for rent for boys in Pallikaranai",
            "Room for rent for girls in Chennai",
            "Room for rent for girls in Pallikaranai",
            "House for rent in Chennai",
            "House for rent in Pallikaranai",
            "1 RK on rent in Chennai",
            "1 RK on rent in Pallikaranai",
            "1 RK on rent for boys in Chennai",
            "1 RK on rent for boys in Pallikaranai",
            "1 RK on rent for girls in Chennai",
            "1 RK on rent for girls in Pallikaranai",
            "1 BHK House for rent in Chennai",
            "1 BHK House for rent in Pallikaranai",
            "2 BHK House for rent in Chennai",
            "2 BHK House for rent in Pallikaranai",
            "3 BHK House for rent in Chennai",
            "3 BHK House for rent in Pallikaranai",
            "4 BHK House for rent in Chennai",
            "4 BHK House for rent in Pallikaranai"],
        CommonRoom:["Room for rent in Sholinganallur",
            "Room for rent in Siruseri",
            "Room for rent for boys in Sholinganallur",
            "Room for rent for boys in Siruseri",
            "Room for rent for girls in Sholinganallur",
            "Room for rent for girls in Siruseri",
            "House for rent in Sholinganallur",
            "House for rent in Siruseri",
            "1 RK on rent in Sholinganallur",
            "1 RK on rent in Siruseri",
            "1 RK on rent for girls in Sholinganallur",
            "1 RK on rent for girls in Siruseri",
            "1 RK on rent for boys in Sholinganallur",
            "1 RK on rent for boys in Siruseri",
            "1 BHK House for rent in Sholinganallur",
            "1 BHK House for rent in Siruseri",
            "2 BHK House for rent in Sholinganallur",
            "2 BHK House for rent in Siruseri",
            "3 BHK House for rent in Sholinganallur",
            "3 BHK House for rent in Siruseri",
            "4 BHK House for rent in Sholinganallur",
            "4 BHK House for rent in Siruseri"],
        CommonPG:["Room for rent in Thuraipakkam",
            "Room for rent in Velachery",
            "Room for rent for boys in Thuraipakkam",
            "Room for rent for boys in Velachery",
            "Room for rent for girls in Thuraipakkam",
            "Room for rent for girls in Velachery",
            "House for rent in Thuraipakkam",
            "House for rent in Velachery",
            "1 RK on rent in Thuraipakkam",
            "1 RK on rent in Velachery",
            "1 RK on rent for boys in Thuraipakkam",
            "1 RK on rent for boys in Velachery",
            "1 RK on rent for girls in Thuraipakkam",
            "1 RK on rent for girls in Velachery",
            "1 BHK House for rent in Thuraipakkam",
            "1 BHK House for rent in Velachery",
            "2 BHK House for rent in Thuraipakkam",
            "2 BHK House for rent in Velachery",
            "3 BHK House for rent in Thuraipakkam",
            "3 BHK House for rent in Velachery",
            "4 BHK House for rent in Thuraipakkam",
            "4 BHK House for rent in Velachery"]
    },

    Delhi:{
        SearchResult:["Room for rent in Delhi",
            "Room for rent in Greater Kailash 1",
            "Room for rent for boys in Delhi",
            "Room for rent for boys in Greater Kailash 1",
            "Room for rent for girls in Delhi",
            "Room for rent for girls in Greater Kailash 1",
            "House for rent in Delhi",
            "House for rent in Greater Kailash 1",
            "1 RK on rent in Delhi",
            "1 RK on rent in Greater Kailash 1",
            "1 RK on rent for boys in Delhi",
            "1 RK on rent for boys in Greater Kailash 1",
            "1 RK on rent for girls in Delhi",
            "1 RK on rent for girls in Greater Kailash 1",
            "1 BHK House for rent in Delhi",
            "1 BHK House for rent in Greater Kailash 1",
            "2 BHK House for rent in Delhi",
            "2 BHK House for rent in Greater Kailash 1",
            "3 BHK House for rent in Delhi",
            "3 BHK House for rent in Greater Kailash 1",
            "4 BHK House for rent in Delhi",
            "4 BHK House for rent in Greater Kailash 1"],
        CommonRoom:["Room for rent in Kalkaji",
            "Room for rent in Mayur Vihar Phase 1",
            "Room for rent for boys in Kalkaji",
            "Room for rent for boys in Mayur Vihar Phase 1",
            "Room for rent for girls in Kalkaji",
            "Room for rent for girls in Mayur Vihar Phase 1",
            "House for rent in Kalkaji",
            "House for rent in Mayur Vihar Phase 1",
            "1 RK on rent in Kalkaji",
            "1 RK on rent in Mayur Vihar Phase 1",
            "1 RK on rent for boys in Kalkaji",
            "1 RK on rent for boys in Mayur Vihar Phase 1",
            "1 RK on rent for girls in Kalkaji",
            "1 RK on rent for girls in Mayur Vihar Phase 1",
            "1 BHK House for rent in Kalkaji",
            "1 BHK House for rent in Mayur Vihar Phase 1",
            "2 BHK House for rent in Kalkaji",
            "2 BHK House for rent in Mayur Vihar Phase 1",
            "3 BHK House for rent in Kalkaji",
            "3 BHK House for rent in Mayur Vihar Phase 1",
            "3 BHK House for rent in Kalkaji",
            "3 BHK House for rent in Mayur Vihar Phase 1"],
        CommonPG:["Room for rent in Sarita Vihar",
            "Room for rent in Sector 10 Dwarka",
            "Room for rent for boys in Sarita Vihar",
            "Room for rent for boys in Sector 10 Dwarka",
            "Room for rent for girls in Sarita Vihar",
            "Room for rent for girls in Sector 10 Dwarka",
            "House for rent in Sarita Vihar",
            "House for rent in Sector 10 Dwarka",
            "1 RK on rent in Sarita Vihar",
            "1 RK on rent in Sector 10 Dwarka",
            "1 RK on rent for boys in Sarita Vihar",
            "1 RK on rent for boys in Sector 10 Dwarka",
            "1 RK on rent for girls in Sarita Vidar",
            "1 RK on rent for girls in Sector 10 Dwarka",
            "1 BHK House for rent in Sarita Vihar",
            "1 BHK House for rent in Sector 10 Dwarka",
            "2 BHK House for rent in Sarita Vihar",
            "2 BHK House for rent in Sector 10 Dwarka",
            "3 BHK House for rent in Sarita Vihar",
            "3 BHK House for rent in Sector 10 Dwarka",
            "4 BHK House for rent in Sarita Vihar",
            "4 BHK House for rent in Sector 10 Dwarka"]
    },

    Gurgaon:{
        SearchResult:[],
        CommonRoom:[],
        CommonPG:[]
    },

    Hyderabad:{
        SearchResult:[],
        CommonRoom:[],
        CommonPG:[]
    },

    Jaipur:{
        SearchResult:[],
        CommonRoom:[],
        CommonPG:[]
    },

    Kolkata:{
        SearchResult:[],
        CommonRoom:[],
        CommonPG:[]
    },

    Mumbai:{
        SearchResult:[],
        CommonRoom:[],
        CommonPG:[]
    },

    Patna:{
        SearchResult:[],
        CommonRoom:[],
        CommonPG:[]
    },

    Pune:{
        SearchResult:[],
        CommonRoom:[],
        CommonPG:[]
    },
} 
export default cityLinks;