const cityLinks = {
    Bengaluru:{
            SearchResult:["Room for rent in Bangalore",
                "Room for rent in Bellandur",
                "Room for rent for boys in Bangalore",
                "Room for rent for boys in Bellandur",
                "Room for rent for girls in Bangalore",
                "Room for rent for girls in Bellandur",
                "House for rent in Bangalore",
                "House for rent in Bellandur",
                "1RK on rent in Bangalore",
                "1RK on rent in Bellandur",
                "1RK on rent for boys in Bangalore",
                "1RK on rent for boys in Bellandur",
                "1RK on rent for girls in Bangalore",
                "1RK on rent for girls in Bellandur",
                "1 BHK House for rent in Bangalore",
                "1 BHK House for rent in Bellandur",
                "2 BHK House for rent in Bangalore",
                "2 BHK House for rent in Bellandur",
                "3 BHK House for rent in Bangalore",
                "3 BHK House for rent in Bellandur",
                "4 BHK House for rent in Bangalore",
                "4 BHK House for rent in Bellandur"],

            CommonRoom:["Room for rent in Hsr Layout",
                "Room for rent in Marathahalli",
                "Room for rent for boys in Hsr Layout",
                "Room for rent for boys in Marathahalli",
                "Room for rent for girls in Hsr Layout",
                "Room for rent for girls in Marathahalli",
                "House for rent in Hsr Layout",
                "House for rent in Marathahalli",
                "1RK on rent in Hsr Layout",
                "1RK on rent in Marathahalli",
                "1RK on rent for boys in Hsr Layout",
                "1RK on rent for boys in Marathahalli",
                "1RK on rent for girls in Hsr Layout",
                "1RK on rent for girls in Marathahalli",
                "1 BHK House for rent in Hsr Layout",
                "1 BHK House for rent in Marathahalli",
                "2 BHK House for rent in Hsr Layout",
                "2 BHK House for rent in Marathahalli",
                "3 BHK House for rent in Hsr Layout",
                "3 BHK House for rent in Marathahalli",
                "4 BHK House for rent in Hsr Layout",
                "4 BHK House for rent in Marathahalli"],

            CommonPG:["Room for rent in Mahadevapura",
                "Room for rent in Whitefield",
                "Room for rent for boys in Mahadevapura",
                "Room for rent for boys in Whitefield",
                "Room for rent for girls in Mahadevapura",
                "Room for rent for girls in Whitefield",
                "House for rent in Mahadevapura",
                "House for rent in Whitefield",
                "1RK on rent in Mahadevapura",
                "1RK on rent in Whitefield",
                "1RK on rent for boys in Mahadevapura",
                "1RK on rent for boys in Whitefield",
                "1RK on rent for girls in Mahadevapura",
                "1RK on rent for girls in Whitefield",
                "1 BHK House for rent in Mahadevapura",
                "1 BHK House for rent in Whitefield",
                "2 BHK House for rent in Mahadevapura",
                "2 BHK House for rent in Whitefield",
                "3 BHK House for rent in Mahadevapura",
                "3 BHK House for rent in Whitefield",
                "4 BHK House for rent in Mahadevapura",
                "4 BHK House for rent in Whitefield"]
    },

    Chennai:{
        SearchResult:["Room for rent in Chennai",
            "Room for rent in Pallikaranai",
            "Room for rent for boys in Chennai",
            "Room for rent for boys in Pallikaranai",
            "Room for rent for girls in Chennai",
            "Room for rent for girls in Pallikaranai",
            "House for rent in Chennai",
            "House for rent in Pallikaranai",
            "1 RK on rent in Chennai",
            "1 RK on rent in Pallikaranai",
            "1 RK on rent for boys in Chennai",
            "1 RK on rent for boys in Pallikaranai",
            "1 RK on rent for girls in Chennai",
            "1 RK on rent for girls in Pallikaranai",
            "1 BHK House for rent in Chennai",
            "1 BHK House for rent in Pallikaranai",
            "2 BHK House for rent in Chennai",
            "2 BHK House for rent in Pallikaranai",
            "3 BHK House for rent in Chennai",
            "3 BHK House for rent in Pallikaranai",
            "4 BHK House for rent in Chennai",
            "4 BHK House for rent in Pallikaranai"],
        CommonRoom:["Room for rent in Sholinganallur",
            "Room for rent in Siruseri",
            "Room for rent for boys in Sholinganallur",
            "Room for rent for boys in Siruseri",
            "Room for rent for girls in Sholinganallur",
            "Room for rent for girls in Siruseri",
            "House for rent in Sholinganallur",
            "House for rent in Siruseri",
            "1 RK on rent in Sholinganallur",
            "1 RK on rent in Siruseri",
            "1 RK on rent for girls in Sholinganallur",
            "1 RK on rent for girls in Siruseri",
            "1 RK on rent for boys in Sholinganallur",
            "1 RK on rent for boys in Siruseri",
            "1 BHK House for rent in Sholinganallur",
            "1 BHK House for rent in Siruseri",
            "2 BHK House for rent in Sholinganallur",
            "2 BHK House for rent in Siruseri",
            "3 BHK House for rent in Sholinganallur",
            "3 BHK House for rent in Siruseri",
            "4 BHK House for rent in Sholinganallur",
            "4 BHK House for rent in Siruseri"],
        CommonPG:["Room for rent in Thuraipakkam",
            "Room for rent in Velachery",
            "Room for rent for boys in Thuraipakkam",
            "Room for rent for boys in Velachery",
            "Room for rent for girls in Thuraipakkam",
            "Room for rent for girls in Velachery",
            "House for rent in Thuraipakkam",
            "House for rent in Velachery",
            "1 RK on rent in Thuraipakkam",
            "1 RK on rent in Velachery",
            "1 RK on rent for boys in Thuraipakkam",
            "1 RK on rent for boys in Velachery",
            "1 RK on rent for girls in Thuraipakkam",
            "1 RK on rent for girls in Velachery",
            "1 BHK House for rent in Thuraipakkam",
            "1 BHK House for rent in Velachery",
            "2 BHK House for rent in Thuraipakkam",
            "2 BHK House for rent in Velachery",
            "3 BHK House for rent in Thuraipakkam",
            "3 BHK House for rent in Velachery",
            "4 BHK House for rent in Thuraipakkam",
            "4 BHK House for rent in Velachery"]
    },

    Delhi:{
        SearchResult:["Room for rent in Delhi",
            "Room for rent in Greater Kailash 1",
            "Room for rent for boys in Delhi",
            "Room for rent for boys in Greater Kailash 1",
            "Room for rent for girls in Delhi",
            "Room for rent for girls in Greater Kailash 1",
            "House for rent in Delhi",
            "House for rent in Greater Kailash 1",
            "1 RK on rent in Delhi",
            "1 RK on rent in Greater Kailash 1",
            "1 RK on rent for boys in Delhi",
            "1 RK on rent for boys in Greater Kailash 1",
            "1 RK on rent for girls in Delhi",
            "1 RK on rent for girls in Greater Kailash 1",
            "1 BHK House for rent in Delhi",
            "1 BHK House for rent in Greater Kailash 1",
            "2 BHK House for rent in Delhi",
            "2 BHK House for rent in Greater Kailash 1",
            "3 BHK House for rent in Delhi",
            "3 BHK House for rent in Greater Kailash 1",
            "4 BHK House for rent in Delhi",
            "4 BHK House for rent in Greater Kailash 1"],
        CommonRoom:["Room for rent in Kalkaji",
            "Room for rent in Mayur Vihar Phase 1",
            "Room for rent for boys in Kalkaji",
            "Room for rent for boys in Mayur Vihar Phase 1",
            "Room for rent for girls in Kalkaji",
            "Room for rent for girls in Mayur Vihar Phase 1",
            "House for rent in Kalkaji",
            "House for rent in Mayur Vihar Phase 1",
            "1 RK on rent in Kalkaji",
            "1 RK on rent in Mayur Vihar Phase 1",
            "1 RK on rent for boys in Kalkaji",
            "1 RK on rent for boys in Mayur Vihar Phase 1",
            "1 RK on rent for girls in Kalkaji",
            "1 RK on rent for girls in Mayur Vihar Phase 1",
            "1 BHK House for rent in Kalkaji",
            "1 BHK House for rent in Mayur Vihar Phase 1",
            "2 BHK House for rent in Kalkaji",
            "2 BHK House for rent in Mayur Vihar Phase 1",
            "3 BHK House for rent in Kalkaji",
            "3 BHK House for rent in Mayur Vihar Phase 1",
            "3 BHK House for rent in Kalkaji",
            "3 BHK House for rent in Mayur Vihar Phase 1"],
        CommonPG:["Room for rent in Sarita Vihar",
            "Room for rent in Sector 10 Dwarka",
            "Room for rent for boys in Sarita Vihar",
            "Room for rent for boys in Sector 10 Dwarka",
            "Room for rent for girls in Sarita Vihar",
            "Room for rent for girls in Sector 10 Dwarka",
            "House for rent in Sarita Vihar",
            "House for rent in Sector 10 Dwarka",
            "1 RK on rent in Sarita Vihar",
            "1 RK on rent in Sector 10 Dwarka",
            "1 RK on rent for boys in Sarita Vihar",
            "1 RK on rent for boys in Sector 10 Dwarka",
            "1 RK on rent for girls in Sarita Vidar",
            "1 RK on rent for girls in Sector 10 Dwarka",
            "1 BHK House for rent in Sarita Vihar",
            "1 BHK House for rent in Sector 10 Dwarka",
            "2 BHK House for rent in Sarita Vihar",
            "2 BHK House for rent in Sector 10 Dwarka",
            "3 BHK House for rent in Sarita Vihar",
            "3 BHK House for rent in Sector 10 Dwarka",
            "4 BHK House for rent in Sarita Vihar",
            "4 BHK House for rent in Sector 10 Dwarka"]
    },

    Gurgaon:{
        SearchResult:["Room for rent in Gurgaon",
            "Room for rent in Dlf City Phase 3",
            "Room for rent for boys in Gurgaon",
            "Room for rent for boys in Dlf City Phase 3",
            "Room for rent for girls in Gurgaon",
            "Room for rent for girls in Dlf City Phase 3",
            "House for rent in Gurgaon",
            "House for rent in Dlf City Phase 3",
            "1 RK on rent in Gurgaon",
            "1 RK on rent in Dlf City Phase 3",
            "1 RK on rent for boys in Gurgaon",
            "1 RK on rent for boys in Dlf City Phase 3",
            "1 RK on rent for girls in Gurgaon",
            "1 RK on rent for girls in Dlf City Phase 3",
            "1 BHK House for rent in Gurgaon",
            "1 BHK House for rent in Dlf City Phase 3",
            "2 BHK House for rent in Gurgaon",
            "2 BHK House for rent in Dlf City Phase 3",
            "3 BHK House for rent in Gurgaon",
            "3 BHK House for rent in Dlf City Phase 3",
            "4 BHK House for rent in Gurgaon",
            "4 BHK House for rent in Dlf City Phase 3"],
        CommonRoom:["Room for rent in Sector 39",
            "Room for rent in Sector 43",
            "Room for rent for boys in Sector 39",
            "Room for rent for boys in Sector 43",
            "Room for rent for girls in Sector 39",
            "Room for rent for girls in Sector 43",
            "House for rent in Sector 39",
            "House for rent in Sector 43",
            "1 RK on rent in Sector 39",
            "1 RK on rent in Sector 43",
            "1 RK on rent for boys in Sector 39",
            "1 RK on rent for boys in Sector 43",
            "1 RK on rent for girls in Sector 39",
            "1 RK on rent for girls in Sector 43",
            "1 BHK House for rent in Sector 39",
            "1 BHK House for rent in Sector 43",
            "2 BHK House for rent in Sector 39",
            "2 BHK House for rent in Sector 43",
            "3 BHK House for rent in Sector 39",
            "3 BHK House for rent in Sector 43",
            "4 BHK House for rent in Sector 39",
            "4 BHK House for rent in Sector 43"],
        CommonPG:["Room for rent in Sector 52",
            "Room for rent in Sector 57",
            "Room for rent for boys in Sector 52",
            "Room for rent for boys in Sector 57",
            "Room for rent for girls in Sector 52",
            "Room for rent for girls in Sector 57",
            "House for rent in Sector 52",
            "House for rent in Sector 57",
            "1 RK on rent in Sector 52",
            "1 RK on rent in Sector 57",
            "1 RK on rent for boys in Sector 52",
            "1 RK on rent for boys in Sector 57",
            "1 RK on rent for girls in Sector 52",
            "1 RK on rent for girls in Sector 57",
            "1 BHK House for rent in Sector 52",
            "1 BHK House for rent in Sector 57",
            "2 BHK House for rent in Sector 52",
            "2 BHK House for rent in Sector 57",
            "3 BHK House for rent in Sector 52",
            "3 BHK House for rent in Sector 57",
            "4 BHK House for rent in Sector 52",
            "4 BHK House for rent in Sector 57"]
    },

    Hyderabad:{
        SearchResult:["Room for rent in Hyderabad",
            "Room for rent in Gachibowli",
            "Room for rent for boys in Hyderabad",
            "Room for rent for boys in Gachibowli",
            "Room for rent for girls in Hyderabad",
            "Room for rent for girls in Gachibowli",
            "House for rent in Hyderabad",
            "House for rent in Gachibowli",
            "1 RK on rent in Hyderabad",
            "1 RK on rent in Gachibowli",
            "1 RK on rent for boys in Hyderabad",
            "1 RK on rent for boys in Gachibowli",
            "1 RK on rent for girls in Hyderabad",
            "1 RK on rent for girls in Gachibowli",
            "1 BHK House for rent in Hyderabad",
            "1 BHK House for rent in Gachibowli",
            "2 BHK House for rent in Hyderabad",
            "2 BHK House for rent in Gachibowli",
            "3 BHK House for rent in Hyderabad",
            "3 BHK House for rent in Gachibowli",
            "4 BHK House for rent in Hyderabad",
            "4 BHK House for rent in Gachibowli"],
        CommonRoom:["Room for rent in Kondapur",
            "Room for rent in Kukatpally",
            "Room for rent for boys in Kondapur",
            "Room for rent for boys in Kukatpally",
            "Room for rent for girls in Kondapur",
            "Room for rent for girls in Kukatpally",
            "House for rent in Kondapur",
            "House for rent in Kukatpally",
            "1 RK on rent in Kondapur",
            "1 RK on rent in Kukatpally",
            "1 RK on rent for boys in Kondapur",
            "1 RK on rent for boys in Kukatpally",
            "1 RK on rent for girls in Kondapur",
            "1 RK on rent for girls in Kukatpally",
            "1 BHK House for rent in Kondapur",
            "1 BHK House for rent in Kukatpally",
            "2 BHK House for rent in Kondapur",
            "2 BHK House for rent in Kukatpally",
            "3 BHK House for rent in Kondapur",
            "3 BHK House for rent in Kukatpally",
            "4 BHK House for rent in Kondapur",
            "4 BHK House for rent in Kukatpally"],
        CommonPG:["Room for rent in Madhapur",
            "Room for rent in Manikonda",
            "Room for rent for boys in Madhapur",
            "Room for rent for boys in Manikonda",
            "Room for rent for girls in Madhapur",
            "Room for rent for girls in Manikonda",
            "House for rent in Madhapur",
            "House for rent in Manikonda",
            "1 RK on rent in Madhapur",
            "1 RK on rent in Manikonda",
            "1 RK on rent for boys in Madhapur",
            "1 RK on rent for boys in Manikonda",
            "1 RK on rent for girls in Madhapur",
            "1 RK on rent for girls in Manikonda",
            "1 BHK House for rent in Madhapur",
            "1 BHK House for rent in Manikonda",
            "2 BHK House for rent in Madhapur",
            "2 BHK House for rent in Manikonda",
            "3 BHK House for rent in Madhapur",
            "3 BHK House for rent in Manikonda",
            "4 BHK House for rent in Madhapur",
            "4 BHK House for rent in Manikonda"]
    },

    Jaipur:{
        SearchResult:[],
        CommonRoom:[],
        CommonPG:[]
    },

    Kolkata:{
        SearchResult:[],
        CommonRoom:[],
        CommonPG:[]
    },

    Mumbai:{
        SearchResult:["Room for rent in Mumbai",
            "Room for rent in Andheri East",
            "Room for rent in Santacruz East",
            "Room for rent for boys in Andheri West",
            "Room for rent for boys in Kurla West",
            "Room for rent for girls in Andheri East",
            "Room for rent for girls in Andheri West",
            "House for rent in Mumbai",
            "House for rent in Andheri East",
            "House for rent in Santacruz East",
            "1 RK on rent in Andheri West",
            "1 RK on rent in Kurla West",
            "1 RK on rent for boys in Andheri East",
            "1 RK on rent for boys in Andheri West",
            "1 RK on rent for girls in Mumbai",
            "1 RK on rent for girls in Andheri East",
            "1 RK on rent for girls in Santacruz East",
            "1 BHK House for rent in Andheri West",
            "1 BHK House for rent in Kurla West",
            "2 BHK House for rent in Andheri East",
            "2 BHK House for rent in Andheri West",
            "3 BHK House for rent in Mumbai",
            "3 BHK House for rent in Andheri East",
            "3 BHK House for rent in Santacruz East",
            "4 BHK House for rent in Mumbai",
            "4 BHK House for rent in Santacruz East"],
        CommonRoom:["Room for rent in Andheri West",
            "Room for rent in Kurla West",
            "Room for rent for boys in Mumbai",
            "Room for rent for boys in Malad West",
            "Room for rent for boys in Powai",
            "Room for rent for girls in Kurla West",
            "Room for rent for girls in Malad West",
            "House for rent in Andheri West",
            "House for rent in Kurla West",
            "1 RK on rent in Mumbai",
            "1 RK on rent in Malad West",
            "1 RK on rent in Powai",
            "1 RK on rent for boys in Kurla West",
            "1 RK on rent for boys in Malad West",
            "1 RK on rent for girls in Andheri West",
            "1 RK on rent for girls in Kurla West",
            "1 BHK House for rent in Mumbai",
            "1 BHK House for rent in Malad West",
            "1 BHK House for rent in Powai",
            "2 BHK House for rent in Kurla West",
            "2 BHK House for rent in Malad West",
            "3 BHK House for rent in Andheri West",
            "3 BHK House for rent in Kurla West",
            "4 BHK House for rent in Andheri East",
            "4 BHK House for rent in Andheri West",
            "4 BHK House for rent in Powai"],
        CommonPG:["Room for rent in Malad West",
            "Room for rent in Powai",
            "Room for rent for boys in Andheri East",
            "Room for rent for boys in Santacruz East",
            "Room for rent for girls in Mumbai",
            "Room for rent for girls in Powai",
            "Room for rent for girls in Santacruz East",
            "House for rent in Malad West",
            "House for rent in Powai",
            "1 RK on rent in Andheri East",
            "1 RK on rent in Santacruz East",
            "1 RK on rent for boys in Mumbai",
            "1 RK on rent for boys in Powai",
            "1 RK on rent for boys in Santacruz East",
            "1 RK on rent for girls in Malad West",
            "1 RK on rent for girls in Powai",
            "1 BHK House for rent in Andheri East",
            "1 BHK House for rent in Santacruz East",
            "2 BHK House for rent in Mumbai",
            "2 BHK House for rent in Powai",
            "2 BHK House for rent in Santacruz East",
            "3 BHK House for rent in Malad West",
            "3 BHK House for rent in Powai",
            "4 BHK House for rent in Kurla West",
            "4 BHK House for rent in Malad West"]
    },

    Patna:{
        SearchResult:[],
        CommonRoom:[],
        CommonPG:[]
    },

    Pune:{
        SearchResult:["Room for rent in Pune",
            "Room for rent in Hinjewadi",
            "Room for rent for boys in Pune",
            "Room for rent for boys in Hinjewadi",
            "Room for rent for girls in Pune",
            "Room for rent for girls in Hinjewadi",
            "House for rent in Pune",
            "House for rent in Hinjewadi",
            "1 RK on rent in Pune",
            "1 RK on rent in Hinjewadi",
            "1 RK on rent for boys in Pune",
            "1 RK on rent for boys in Hinjewadi",
            "1 RK on rent for girls in Pune",
            "1 RK on rent for girls in Hinjewadi",
            "1 BHK House for rent in Pune",
            "1 BHK House for rent in Hinjewadi",
            "2 BHK House for rent in Pune",
            "2 BHK House for rent in Hinjewadi",
            "3 BHK House for rent in Pune",
            "3 BHK House for rent in Hinjewadi",
            "4 BHK House for rent in Pune",
            "4 BHK House for rent in Hinjewadi"],
        CommonRoom:["Room for rent in Viman Nagar",
            "Room for rent in Aundh",
            "Room for rent for boys in Viman Nagar",
            "Room for rent for boys in Aundh",
            "Room for rent for girls in Viman Nagar",
            "Room for rent for girls in Aundh",
            "House for rent in Viman Nagar",
            "House for rent in Aundh",
            "1 RK on rent in Viman Nagar",
            "1 RK on rent in Aundh",
            "1 RK on rent for boys in Viman Nagar",
            "1 RK on rent for boys in Aundh",
            "1 RK on rent for girls in Viman Nagar",
            "1 RK on rent for girls in Aundh",
            "1 BHK House for rent in Viman Nagar",
            "1 BHK House for rent in Aundh",
            "2 BHK House for rent in Viman Nagar",
            "2 BHK House for rent in Aundh",
            "3 BHK House for rent in Viman Nagar",
            "3 BHK House for rent in Aundh",
            "4 BHK House for rent in Viman Nagar",
            "4 BHK House for rent in Aundh"],
        CommonPG:["Room for rent in Kharadi",
            "Room for rent in Wakad",
            "Room for rent for boys in Kharadi",
            "Room for rent for boys in Wakad",
            "Room for rent for girls in Kharadi",
            "Room for rent for girls in Wakad",
            "House for rent in Kharadi",
            "House for rent in Wakad",
            "1 RK on rent in Kharadi",
            "1 RK on rent in Wakad",
            "1 RK on rent for boys in Kharadi",
            "1 RK on rent for boys in Wakad",
            "1 RK on rent for girls in Kharadi",
            "1 RK on rent for girls in Wakad",
            "1 BHK House for rent in Kharadi",
            "1 BHK House for rent in Wakad",
            "2 BHK House for rent in Kharadi",
            "2 BHK House for rent in Wakad",
            "3 BHK House for rent in Kharadi",
            "3 BHK House for rent in Wakad",
            "4 BHK House for rent in Kharadi",
            "4 BHK House for rent in Wakad"]
    },
} 
export default cityLinks;